imports:
    - { resource: parameters.yml }
    - { resource: security.yml }

framework:
    #esi:             ~
    translator:      { fallback: "%locale%" }
    secret:          "%secret%"
    router:
        resource: "%kernel.root_dir%/config/routing.yml"
        strict_requirements: ~
    form:            ~
    csrf_protection: ~
    validation:      { enable_annotations: true }
    templating:
        engines: ['twig']
        #assets_version: SomeVersionScheme
    default_locale:  "%locale%"
    trusted_hosts:   ~
    trusted_proxies: ~
    session:
        # handler_id set to null will use default session handler from php.ini
        handler_id:  ~
    fragments:       ~
    http_method_override: true

# Twig Configuration
twig:
    debug:            "%kernel.debug%"
    strict_variables: "%kernel.debug%"
    form:
        resources:
            - BraincraftedBootstrapBundle:Form:bootstrap.html.twig

# Assetic Configuration
assetic:
    filters:
        less: ~
        cssrewrite: ~
    debug:                '%kernel.debug%'
    use_controller: false
    write_to:             '%kernel.root_dir%/../web'
    bundles:
    #java: /usr/bin/java
    assets:
        bootstrap_css:
            inputs:
                - %kernel.root_dir%/Resources/less/bootstrap.less
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/less/form.less
            filters:
                - less
                - cssrewrite
            output: css/bootstrap.css
        jquery:
            inputs:
                - %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
            output: js/jquery.js
        bootstrap_js:
            inputs:
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/transition.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/alert.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/button.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/carousel.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/collapse.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/dropdown.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/modal.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tooltip.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/popover.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/scrollspy.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/tab.js
                - %kernel.root_dir%/../vendor/twbs/bootstrap/js/affix.js
                - %kernel.root_dir%/../vendor/braincrafted/bootstrap-bundle/Braincrafted/Bundle/BootstrapBundle/Resources/js/bc-bootstrap-collection.js
            output: js/bootstrap.js
        jsperso:
            inputs:
                - %kernel.root_dir%/Resources/js/jsperso.js
            output: js/jsperso.js

braincrafted_bootstrap:
    output_dir: %kernel.root_dir%/../web/bootstrap
    assets_dir: %kernel.root_dir%/../vendor/twbs/bootstrap
    jquery_path: %kernel.root_dir%/../vendor/jquery/jquery/jquery-1.11.1.js
    css_preprocessor: less # "less", "lessphp", "sass" or "none"
    fonts_dir: %kernel.root_dir%/../web/fonts
    auto_configure:
        assetic: false
        twig: false
        knp_menu: false
        knp_paginator: false
    customize:
        variables_file: %kernel.root_dir%/Resources/less/variables.less
        bootstrap_output: %kernel.root_dir%/Resources/less/bootstrap.less
        bootstrap_template: BraincraftedBootstrapBundle:Bootstrap:bootstrap.less.twig
    icon_prefix: glyphicon fontawesome_dir: %kernel.root_dir%/../vendor/fortawesome/font-awesome

fos_js_routing:
    routes_to_expose: [ tg_client_view, set_dimensions, set_projets, set_contacts, tg_prod_view ]

# Doctrine Configuration
doctrine:
    dbal:
        driver:   "%database_driver%"
        host:     "%database_host%"
        port:     "%database_port%"
        dbname:   "%database_name%"
        user:     "%database_user%"
        password: "%database_password%"
        charset:  UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: "%kernel.root_dir%/data/data.db3"
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #     path:     "%database_path%"

    orm:
        auto_generate_proxy_classes: "%kernel.debug%"
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: "%mailer_transport%"
    host:      "%mailer_host%"
    username:  "%mailer_user%"
    password:  "%mailer_password%"
    spool:     { type: memory }

# Stof\DoctrineExtensionBundle configuration
stof_doctrine_extensions:
    orm:
        default:
            sluggable: true

fos_user:
    db_driver:     orm                       # Le type de BDD à utiliser, nous utilisons l'ORM Doctrine depuis le début
    firewall_name: main                      # Le nom du firewall derrière lequel on utilisera ces utilisateurs
    user_class:    TG\UserBundle\Entity\User # La classe de l'entité User que nous utilisons
    registration:
        confirmation:
            from_email:
                address :    inscription@technograv.fr
                sender_name: Technograv.prod
    resetting:
        email:
            from_email:
                address:    reinitialiser@technograv.fr
                sender_name: Technograv.prod
    from_email:
        address:    noreply@technograv.fr
        sender_name: Technograv.prod

liip_imagine:
    resolvers:
        default:
            web_path: ~

    filter_sets:
        cache: ~
        logo:
            quality: 75
            filters:
                relative_resize: { widen: 200 }
        login:
            quality: 75
            filters:
                relative_resize: { widen: 600 }

services:
    twig.extension.intl:
       class: Twig_Extensions_Extension_Intl
       tags:
           - { name: twig.extension }

    twig.extension.text:
       class: Twig_Extensions_Extension_Text
       tags:
           - { name: twig.extension }

    fos_user.doctrine_registry:
        alias: doctrine

genemu_form:
    date: ~
    select2: ~

knp_paginator:
    page_range: 5                      # default page range used in pagination control
    default_options:
        page_name: page                # page query parameter name
        sort_field_name: sort          # sort field query parameter name
        sort_direction_name: direction # sort direction query parameter name
        distinct: true                 # ensure distinct results, useful when ORM queries are using GROUP BY statements
    template:
        pagination: KnpPaginatorBundle:Pagination:twitter_bootstrap_v3_pagination.html.twig     # sliding pagination controls template
        sortable: KnpPaginatorBundle:Pagination:sortable_link.html.twig # sort link template

fos_elastica:
    clients:
        default: { host: localhost, port: 9200 }
    indexes:
        test1:
            client: default
            settings:
                index:
                    analysis:
                        analyzer:
                            custom_analyzer :
                                type     :    custom
                                tokenizer:    nGram
                                filter   :    [stopwords, asciifolding ,lowercase, snowball, elision, worddelimiter]
                            custom_search_analyzer :
                                type     :    custom
                                tokenizer:    standard
                                filter   :    [asciifolding ,lowercase, snowball, elision, worddelimiter]
                        tokenizer:
                            nGram:
                                type:     nGram
                                min_gram: 3
                                max_gram: 20
                        filter:
                            snowball:
                                type:     snowball
                                language: French
                            elision:
                                type:     elision
                                articles: [l, m, t, qu, n, s, j, d]
                            stopwords:
                                type:      stop
                                stopwords: [_french_]
                                ignore_case : true
                            worddelimiter :
                                type:      word_delimiter
            types:
                client:
                    mappings:
                        name:
                            boost: 3
                            index_analyzer : custom_analyzer
                            search_analyzer : custom_search_analyzer
                    persistence:
                        driver: orm
                        model: TG\ClientBundle\Entity\Client
                        provider: ~
                        listener: ~
                        finder: ~
                contact:
                    mappings:
                        name:
                            boost: 3
                            index_analyzer : custom_analyzer
                            search_analyzer : custom_search_analyzer
                        email: ~
                        client:
                            type: object
                            properties:
                                name: ~
                                id:
                                    type: integer
                    persistence:
                        driver: orm
                        model: TG\ClientBundle\Entity\Contact
                        provider: ~
                        listener: ~
                        finder: ~
                projet:
                    mappings:
                        titre:
                            boost: 3
                            index_analyzer : custom_analyzer
                            search_analyzer : custom_search_analyzer
                            limit: 0
                        contenu:
                            boost: 3
                            index_analyzer : custom_analyzer
                            search_analyzer : custom_search_analyzer
                            limit: 0
                    persistence:
                        driver: orm
                        model: TG\ProdBundle\Entity\Projet
                        provider: ~
                        listener: ~
                        finder: ~
