# you can read more about security in the related section of the documentation
# http://symfony.com/doc/current/book/security.html
security:
    # http://symfony.com/doc/current/book/security.html#encoding-the-user-s-password
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext
        TG\UserBundle\Entity\User: sha512

    # http://symfony.com/doc/current/book/security.html#hierarchical-roles
    role_hierarchy:
        ROLE_ATELIER:     [ROLE_STAGIAIRE]
        ROLE_PAO:         [ROLE_ATELIER]
        ROLE_COMPTA:      [ROLE_PAO]
        ROLE_GERANT:      [ROLE_COMPTA]
        ROLE_ADMIN:       [ROLE_GERANT]
        ROLE_SUPER_ADMIN: [ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # http://symfony.com/doc/current/book/security.html#where-do-users-come-from-user-providers
    providers:
        main:
            id: fos_user.user_provider.username

    # the main part of the security, where you can set up firewalls
    # for specific sections of your app
    firewalls:
        login:
            pattern:    ^/login$
            anonymous:   true

        reset:
            pattern:    ^/resetting/.*$
            anonymous:    true

        dev:
            pattern:  ^/(_(profiler|wdt)|css|images|js)/
            security: false

        main:
            pattern:    ^/
            anonymous:  false
            provider:   main
            form_login:
                login_path: fos_user_security_login
                check_path: fos_user_security_check
                default_target_path: /prod
            logout:
                path:   fos_user_security_logout
                target: /login
            remember_me:
                key:    %secret%

    access_control:
        #- { path: ^/admin, roles: ROLE_ADMIN }
