<?php

namespace TG\ProdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
	public function getComments($projet/*, $page, $nbPerPage*/)
	{
		$qb = $this->createQueryBuilder('c')
			->where('c.projet = :projet')
			->setParameter('projet', $projet)
			->orderBy('c.date', 'ASC');

		return $qb
			->getQuery()
			->getResult();
	}
}
