<?php

namespace TG\ProdBundle\Entity;

use Doctrine\ORM\EntityRepository;
use Doctrine\ORM\QueryBuilder;
use Doctrine\ORM\Tools\Pagination\Paginator;

/**
 * CommentaireRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CommentaireRepository extends EntityRepository
{
	public function getComments($projet/*, $page, $nbPerPage*/)
	{
		$qb = $this->createQueryBuilder('c')
			->where('c.projet = :projet')
			->setParameter('projet', $projet)
			->orderBy('c.date', 'ASC');
		/*	->getQuery()
			->setFirstResult(($page-1) * $nbPerPage)
			->setMaxResults($nbPerPage);

		return new Paginator($qb, true); */

		return $qb
			->getQuery()
			->getResult();
	}
}
