<?php

namespace TG\ProdBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DocumentjointRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocumentjointRepository extends EntityRepository
{
	public function getLastDoc($projet)
	{
		$qb = $this->createQueryBuilder('d');

		$qb
			->where('d.projet = :projet')
			->setParameter('projet', $projet)
			->orderBy('d.date', 'DESC');

		return $qb
			->getQuery()
			->getResult();
	}
}
