#tg_compta_homepage:
 #   path:     /
  #  defaults: { _controller: TGComptaBundle:Default:index }

set_dimensions:
    path: /set_dimensions
    defaults: { _controller: TGComptaBundle:Stock:setdimensions }
    requirements:
        _method: POST

tg_compta_paye:
    path:      /profil
    defaults:  { _controller: TGComptaBundle:Paye:profil }
