tg_compta_homepage:
    path:     /hello/{name}
    defaults: { _controller: TGComptaBundle:Default:index }

set_dimensions:
    pattern: /set_dimensions
    defaults: { _controller:TGComptaBundle:Stock:setdimensions }
    requirements:
        _method: POST
