# src/TG/ProdBundle/Resources/config/routing.yml

tg_prod_home:
    path:      /
    defaults:  { _controller: TGProdBundle:Projet:index }

tg_prod_view:
    path:      /projet/{id}
    defaults:  { _controller: TGProdBundle:Projet:view }
    requirements:
        id: ^[0-9]+$

tg_prod_add:
    path:      /add
    defaults:  { _controller: TGProdBundle:Projet:add }

tg_prod_edit:
    path:      /edit/{id}
    defaults:  { _controller: TGProdBundle:Projet:edit }
    requirements:
        id: ^[0-9]+$

tg_prod_delete:
    path:      /delete/{id}
    defaults:  { _controller: TGProdBundle:Projet:delete }
    requirements:
        id: ^[0-9]+$

tg_prod_next:
    path: /next/{id}
    defaults: { _controller: TGProdBundle:Projet:next }
    requirements:
        id: ^[0-9]+$

tg_prod_fichier:
    path: /fichier/{id}
    defaults: { _controller: TGProdBundle:Projet:fichier }
    requirements:
       id: ^[0-9]+$

tg_prod_archives:
    path: /archives/
    defaults:   { _controller: TGProdBundle:Projet:archives, page: 1 }
