<?php

namespace TG\ClientBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * ClientRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ClientRepository extends EntityRepository
{
	public function clientIndex($sort, $direction)
		{
			$qb = $this->createQueryBuilder('c');

			$qb
				->orderBy($sort, $direction);

			return $qb->getQuery()->getResult();
		}
}
