<?php

namespace TG\ComptaBundle\Entity;

/**
 * BesoinRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BesoinRepository extends \Doctrine\ORM\EntityRepository
{
	public function findBesoins($stock, $dimension)
	{
		$qb = $this->createQueryBuilder('b');

		$qb
			->where('b.stock = :stock')
			->andwhere('b.dimension = :dimension')
			->setParameter('stock', $stock)
			->setParameter('dimension', $dimension);

		$qb
			->getQuery()
			->getResult();
	}
}
