<?php

namespace TG\ComptaBundle\Entity;

/**
 * DimensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DimensionRepository extends \Doctrine\ORM\EntityRepository
{
}
