<?php

namespace TG\ComptaBundle\Entity;

/**
 * DimensionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DimensionRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByName()
	{
		$qb = $this->createQueryBuilder('d');

		$qb
			->orderBy('d.name', 'ASC');

		return $qb
			->getQuery()
			->getResult();
	}

	public function getDimensionASC()
	{
		$qb = $this->createQueryBuilder('d');

		$qb
			->orderBy('d.name', 'ASC');

		return $qb;
	}
}
