<?php

namespace TG\ComptaBundle\Entity;

/**
 * HeuresupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HeuresupRepository extends \Doctrine\ORM\EntityRepository
{
}
