<?php

namespace TG\ComptaBundle\Entity;

/**
 * StockRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class StockRepository extends \Doctrine\ORM\EntityRepository
{
	public function findAllOrderedByName()
	{
		$qb = $this->createQueryBuilder('s');

		$qb
			->orderBy('s.name', 'ASC');

		return $qb
			->getQuery()
			->getResult();
	}
}
