<?php

namespace TG\CreaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CreaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CreaRepository extends EntityRepository
{
	public function getLastCrea($projet)
	{
		$qb = $this->createQueryBuilder('c');

		$qb
			->where('c.projet = :projet')
			->setParameter('projet', $projet)
			->orderBy('c.dateadd', 'DESC')
			->SetMaxResults(1, 1);

		return $qb
			->getQuery()
			->getResult();
	}
}
