<?php

namespace TG\CreaBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LogoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LogoRepository extends EntityRepository
{
	public function getLogoView($client)
	{
		$qb = $this->createQueryBuilder('l');

		$qb	
			->where('l.client = :client')
			->andwhere('l.extention = :ext')
				->orwhere('l.extention = :ext2')
				->orwhere('l.extention = :ext3')
			->setParameter('client', $client)
			->setParameter('ext', 'jpg')
			->setParameter('ext2', 'png')
			->setParameter('ext3', 'jpeg')
			->orderBy('l.date', 'DESC')
			->setMaxResults( 1 );

		return $qb
			->getQuery()
			->getResult();

	}

		public function getListLogo($client)
	{
		$qb = $this->createQueryBuilder('l');

		$qb	
			->where('l.client = :client')
			->setParameter('client', $client)
			->orderBy('l.date', 'DESC')
			->setMaxResults( 1 );

		return $qb
			->getQuery()
			->getResult();

	}
}
