# src/TG/ClientBundle/Resources/config/routing.yml

tg_client_home:
    path:      /
    defaults:  { _controller: TGClientBundle:Client:index }

tg_client_view:
    path:      /client/{id}
    defaults:  { _controller: TGClientBundle:Client:view }
    requirements:
        id: ^[0-9]+$

tg_client_add:
    path:      /client/add
    defaults:  { _controller: TGClientBundle:Client:add }

tg_client_edit:
    path:      /client/edit/{id}
    defaults:  { _controller: TGClientBundle:Client:edit }
    requirements:
        id: ^[0-9]+$

tg_client_delete:
    path:      /client/delete/{id}
    defaults:  { _controller: TGClientBundle:Client:delete }
    requirements:
        id: ^[0-9]+$

set_contacts:
    pattern: /set_contacts
    defaults: { _controller:TGClientBundle:Contact:setcontacts }
    requirements:
        _method: POST

edit_contact:
    path:   /contact/edit/{id}
    defaults: { _controller: TGClientBundle:Contact:edit }
    requirements:
        id: ^[0-9]+$

tg_contact_home:
    path:   /contact
    defaults: { _controller: TGClientBundle:Contact:index }

set_projets:
    pattern: /set_projets
    defaults: { _controller:TGClientBundle:Contact:setprojets }
    requirements:
        _method: POST
